### ISSUE TITLE
Move the configuration reading phase on the initialization for SDTmonitor.

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/srt-single-dish-tools#126]
Right now the configuration file gets read every time the `process` method gets called to process a '.fits' file. This allows the users to change the configuration file between two files to process, but adds an overhead every time a new file gets created/modified. Since the monitor is supposed to be autonomous, I think that a more appropriate behavior should be to read the configuration at initialization phase and stick with that configuration until the execution is completed/stopped.
@matteobachetti what do you think about it?

**Comment by matteobachetti** [comment]
Go for it!
