### ISSUE TITLE
Multiprocessing monitor can slow down writing on backend disk.

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/srt-single-dish-tools#144]
This is a top priority.
I tested it on my PC, but I was fooled by my PC's disk, which is an SSD, with no mechanical latency. With a mechanical hard disk, trying to read multiple files concurrently can slow down the disk too much, especially when the backend is writing another file. The file writing could get delayed causing some issues related to the backend and/or to the DISCOS control system.
Since knowing how many processes can run properly without slowing the backend down is very difficult, we can follow a different approach: process only the latest received file.
t0: first file 0.fits arrives
t1: 0.fits gets processed
t2: 1.fits arrives and gets enqueued
t3: 2.fits arrives and gets enqueues
t4: 0.fits finished to be processed
t5: 1.fits gets discarded because is too old
t6: 2.fits gets processed and so on

**Comment by matteobachetti** [comment]
@giuseppe-carboni  Ok, go ahead!

**Comment by giuseppe-carboni** [comment]
This was probably a false issue. Latest observations showed no difference between quicklook enabled and quicklook disabled.
