### ISSUE TITLE
Matplotlib does not accept `jpg` format anymore

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/srt-single-dish-tools#171]
The default image format should be changed to something else, I suggest to use `png` instead.

**Comment by matteobachetti** [comment]
Is `pillow` installed? It is needed in current versions of matplotlib (Sorry I saw the PR before the issue)

**Comment by giuseppe-carboni** [comment]
On my PC, tests that output jpg images actually need pillow to be installed. It was never installed on travis.ci for tests in the past. This probably made me think that jpg support was dropped unexpectedly. We can solve this issue in 2 different ways:
- Replace default images extension with a different one, mention somewhere that jpg is still supported but `pillow` package is required.
- Install `pillow` package as a requirement for tests that are failing.
I don't think page loading time could actually be an issue, the processing of some files already takes several seconds to be completed, loading png instead of jpg can only add few milliseconds, which I think are negligible.
By the way, you should decide which of the two strategy is better to adopt, or propose a better approach if you have it.

**Comment by matteobachetti** [comment]
The `pillow` problem has been know for a while, I'm actually surprised it only came out now :).
If page loading is not an issue, we can use png as you did rather than adding an additional dependency. Feel free to merge
