### ISSUE TITLE
The 'workers' option seems super slow

### ISSUE THREAD

**Issue by matteobachetti** [discos/srt-single-dish-tools#177]
I notice that many tests time out at `srttools/tests/test_monitor.py::TestMonitor::test_workers` before completing the analysis of both files, and it seems strange because the total time spent is more than analyzing the files separately.

We should investigate this properly

**Comment by giuseppe-carboni** [comment]
I think this is due to the way the test has been rewritten before my latest overhaul. Now it seems to be working fine. I'll close this issue whenever we merge the new monitor-related branch

**Comment by giuseppe-carboni** [comment]
Fixed in #181, closing.
