### ISSUE TITLE
Quicklook sometimes outputs big files, the directory where the monitor was launched grew to >14GB

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/srt-single-dish-tools#207]
`2021-04-17 10:50:55 - Loading file /roach2_nuraghe/data/ASI/20210417/20210417-103616-ASI-CasA_PmapAZ/20210417-104755-ASI-CasA_PmapAZ_001_013.fits, pid 101605
2021-04-17 10:50:55 - Loading file /roach2_nuraghe/data/ASI/20210417/20210417-103616-ASI-CasA_PmapAZ/20210417-104651-ASI-CasA_PmapAZ_001_012.fits, pid 101606
WARNING: Derotator angle looks weird. Setting to 0 [srttools.io]
WARNING:astropy:Derotator angle looks weird. Setting to 0
WARNING: Derotator angle looks weird. Setting to 0 [srttools.io]
WARNING:astropy:Derotator angle looks weird. Setting to 0
INFO:astropy:The data set is large. Using partial data dumps
INFO:astropy:The data set is large. Using partial data dumps
INFO:astropy:The data set is large. Using partial data dumps
2021-04-17 10:51:14 - [Errno 28] No space left on device`

The output files were named weirdly (the file names were mostly numbers), and they had .p extension. I will investigate whether this bug is due to some SDTools error or some Zmonitor error.

**Comment by matteobachetti** [comment]
This is from `pickle_or_not`, called during the calculation of statistics in data files. When data sets are large, results are partially pickled. In this particular case, there might be a condition I haven't observed during testing. We can disable the functionality
