### ISSUE TITLE
HOR (Az-El) projection

### ISSUE THREAD

**Issue by SbianchiArcetri** [discos/srt-single-dish-tools#223]
Will it be possible to produce maps in the HOR (Az-El) frame centered on a source? It will be useful to produce HOR maps of  the beam from observations of a point source.

**Comment by matteobachetti** [comment]
Hi @SbianchiArcetri! It is already possible, you need to specify `--altaz` as an option to SDTimage

**Comment by matteobachetti** [comment]
Closing unless the problem still persists.
