### ISSUE TITLE
New  version summary fits file name  not handled

### ISSUE THREAD

**Issue by sergiopoppi** [discos/srt-single-dish-tools#240]
Summary files in DISCOS have changed name. New summary file name  is in the following format: 
 
Sum_DATEFirstSubscan-UTFirstSubscan-PROJID-OBJECT.fits

Further information in: 
[https://github.com/discos/discos/issues/348](https://github.com/discos/discos/issues/348)

**Comment by matteobachetti** [comment]
@sergiopoppi @aorlati @giuseppe-carboni could you provide a small example dataset, so that I can test my changes?
