### ISSUE TITLE
Error in the solar imaging procedure (SRT map)

### ISSUE THREAD

**Issue by mmarongiu** [discos/srt-single-dish-tools#244]
Could you fix this error in the solar imaging for SRT, please?
Moreover, I would point out that the imaging procedure for only 1 feed takes approximately 15 minutes.

Thank you, Marco

___________
(base) user@PC:/Ubuntu2204/$ SDTimage KKG_SARDARA_SUN.ini --frame sun
 [I] 2024-08-28 16:06:36 numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
 [I] 2024-08-28 16:06:36 numexpr.utils: NumExpr defaulting to 8 threads.
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 295/295 [16:06<00:00,  3.28s/it]
Traceback (most recent call last):
  File "/home/bins/anaconda3/lib/python3.11/site-packages/srttools/imager.py", line 1245, in write
    super(ScanSet, self).write(fname, *args, **kwargs)
  File "/home/bins/anaconda3/lib/python3.11/site-packages/astropy/table/connect.py", line 130, in __call__
    self.registry.write(instance, *args, **kwargs)
  File "/home/bins/anaconda3/lib/python3.11/site-packages/astropy/io/registry/core.py", line 381, in write
    format = self._get_valid_format(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bins/anaconda3/lib/python3.11/site-packages/astropy/io/registry/base.py", line 359, in _get_valid_format
    raise IORegistryError(
astropy.io.registry.base.IORegistryError: Format could not be identified based on the file name or contents, please provide a 'format' argument.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No
               ascii.aastex  Yes   Yes            No
                ascii.basic  Yes   Yes            No
     ascii.commented_header  Yes   Yes            No
                  ascii.csv  Yes   Yes           Yes
                 ascii.ecsv  Yes   Yes           Yes
           ascii.fast_basic  Yes   Yes            No
ascii.fast_commented_header  Yes   Yes            No
             ascii.fast_csv  Yes   Yes            No
       ascii.fast_no_header  Yes   Yes            No
             ascii.fast_rdb  Yes   Yes            No
             ascii.fast_tab  Yes   Yes            No
          ascii.fixed_width  Yes   Yes            No
ascii.fixed_width_no_header  Yes   Yes            No
 ascii.fixed_width_two_line  Yes   Yes            No
                 ascii.html  Yes   Yes           Yes
                 ascii.ipac  Yes   Yes            No
                ascii.latex  Yes   Yes           Yes
                  ascii.mrt  Yes   Yes            No
            ascii.no_header  Yes   Yes            No
                  ascii.qdp  Yes   Yes           Yes
                  ascii.rdb  Yes   Yes           Yes
                  ascii.rst  Yes   Yes            No
                  ascii.tab  Yes   Yes            No
                       asdf  Yes   Yes           Yes
                       fits  Yes   Yes           Yes
                       hdf5  Yes   Yes           Yes
                   jsviewer   No   Yes            No
                 pandas.csv  Yes   Yes            No
                pandas.html  Yes   Yes            No
                pandas.json  Yes   Yes            No
                    parquet  Yes   Yes           Yes
                    votable  Yes   Yes           Yes
            votable.parquet   No   Yes            No
                     aastex  Yes   Yes            No        Yes
                        csv  Yes   Yes            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        mrt  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bins/anaconda3/bin/SDTimage", line 8, in <module>
    sys.exit(main_imager())
             ^^^^^^^^^^^^^
  File "/home/bins/anaconda3/lib/python3.11/site-packages/srttools/imager.py", line 1830, in main_imager
    scanset.write(outfile, overwrite=True)
  File "/home/bins/anaconda3/lib/python3.11/site-packages/srttools/imager.py", line 1247, in write
    raise astropy.io.registry.IORegistryError(fname + ": " + str(e))
astropy.io.registry.base.IORegistryError: KKG_SARDARA_SUN.ini: Format could not be identified based on the file name or contents, please provide a 'format' argument.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No
               ascii.aastex  Yes   Yes            No
                ascii.basic  Yes   Yes            No
     ascii.commented_header  Yes   Yes            No
                  ascii.csv  Yes   Yes           Yes
                 ascii.ecsv  Yes   Yes           Yes
           ascii.fast_basic  Yes   Yes            No
ascii.fast_commented_header  Yes   Yes            No
             ascii.fast_csv  Yes   Yes            No
       ascii.fast_no_header  Yes   Yes            No
             ascii.fast_rdb  Yes   Yes            No
             ascii.fast_tab  Yes   Yes            No
          ascii.fixed_width  Yes   Yes            No
ascii.fixed_width_no_header  Yes   Yes            No
 ascii.fixed_width_two_line  Yes   Yes            No
                 ascii.html  Yes   Yes           Yes
                 ascii.ipac  Yes   Yes            No
                ascii.latex  Yes   Yes           Yes
                  ascii.mrt  Yes   Yes            No
            ascii.no_header  Yes   Yes            No
                  ascii.qdp  Yes   Yes           Yes
                  ascii.rdb  Yes   Yes           Yes
                  ascii.rst  Yes   Yes            No
                  ascii.tab  Yes   Yes            No
                       asdf  Yes   Yes           Yes
                       fits  Yes   Yes           Yes
                       hdf5  Yes   Yes           Yes
                   jsviewer   No   Yes            No
                 pandas.csv  Yes   Yes            No
                pandas.html  Yes   Yes            No
                pandas.json  Yes   Yes            No
                    parquet  Yes   Yes           Yes
                    votable  Yes   Yes           Yes
            votable.parquet   No   Yes            No
                     aastex  Yes   Yes            No        Yes
                        csv  Yes   Yes            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        mrt  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes

**Comment by matteobachetti** [comment]
Hi @mmarongiu , can you try the following?
```SDTimage -c KKG_SARDARA_SUN.ini --frame sun```

Note the addition of `-c` before the ini file

**Comment by matteobachetti** [comment]
No worries! Thanks for the followup. I'll close this and open another Issue to verify if the documentation is always clear about this
